from __future__ import annotations

from wafdh.models import ResponseSnapshot
from wafdh.signatures import SignatureMatcher, load_rules


def _snapshot(
    *,
    body: str = "",
    headers: tuple[tuple[str, str], ...] = (),
    status_code: int = 403,
    reason_phrase: str = "Forbidden",
    final_url: str = "https://example.test/",
) -> ResponseSnapshot:
    return ResponseSnapshot(
        request_url="https://example.test/",
        final_url=final_url,
        status_code=status_code,
        reason_phrase=reason_phrase,
        headers=headers,
        body_excerpt=body,
    )


def _names(response: ResponseSnapshot) -> tuple[str, ...]:
    matcher = SignatureMatcher(load_rules())
    return tuple(detection.name for detection in matcher.match((response,)))


def test_cloudflare_server_header_alone_is_not_waf_signature() -> None:
    response = _snapshot(headers=(("server", "cloudflare"),), status_code=200)

    assert "Cloudflare WAF" not in _names(response)


def test_cloudflare_challenge_body_is_waf_signature() -> None:
    response = _snapshot(
        headers=(("server", "cloudflare"), ("cf-ray", "a153b8987cd032fa")),
        body="<title>Attention Required! | Cloudflare</title> window.__CF$cv$params = {};",
    )

    assert "Cloudflare WAF" in _names(response)


def test_aws_cloudfront_request_id_alone_is_not_waf_signature() -> None:
    response = _snapshot(
        headers=(("x-amz-cf-id", "abc"), ("x-amzn-requestid", "req")),
        status_code=403,
    )

    assert "AWS WAF" not in _names(response)


def test_aws_managed_rule_block_header_is_waf_signature() -> None:
    response = _snapshot(
        headers=(
            ("x-blocked-by-waf", "Blocked_by_custom_response_for_AWSManagedRulesCommonRuleSet"),
        )
    )

    assert "AWS WAF" in _names(response)


def test_hmg_cloud_waf_is_not_folded_into_penta_wapples() -> None:
    response = _snapshot(
        body=(
            "The request / response that are contrary to the HMG Cloud WAF(Web firewall) "
            "security policies have been blocked. Detect client IP Detect URL"
        )
    )

    assert _names(response) == ("HMG Cloud WAF",)


def test_external_fingerprint_rules_match_distinctive_vendor_markers() -> None:
    cases = (
        (
            "AQTRONIX WebKnight",
            _snapshot(
                status_code=999,
                reason_phrase="No Hacking",
                body="WebKnight Application Firewall Alert",
            ),
        ),
        (
            "Fortinet FortiWeb",
            _snapshot(headers=(("set-cookie", "FORTIWAFSID=123; Path=/"),)),
        ),
        (
            "Wordfence",
            _snapshot(body="This response was generated by Wordfence"),
        ),
        (
            "Cloudbric",
            _snapshot(body="<title>Cloudbric ERROR!</title>Your request was blocked by Cloudbric"),
        ),
        (
            "Datadog App and API Protection",
            _snapshot(
                body='{"detail":"Security provided by Datadog","security_response_id":"abc"}'
            ),
        ),
        (
            "open-appsec",
            _snapshot(
                headers=(("x-request-id", "eadda0d42b6a667ce1985b0b6cb0d8bd"),),
                body=(
                    "<!DOCTYPE HTML><title>403 - Forbidden</title>"
                    "<h2>Forbidden - ID: eadda0d42b6a667ce1985b0b6cb0d8bd</h2>"
                ),
            ),
        ),
        (
            "MOVEC WAF",
            _snapshot(
                body="<title>Blocked</title>",
                final_url="https://waf.movec.services/blocked",
            ),
        ),
        (
            "PerimeterX",
            _snapshot(
                body=(
                    "Access to this page has been denied because we believe you are "
                    "using automation tools"
                ),
            ),
        ),
        (
            "Barracuda WAF",
            _snapshot(headers=(("set-cookie", "barra_counter_session=1; Path=/"),)),
        ),
        (
            "Radware AppWall",
            _snapshot(headers=(("x-sl-compstate", "block"),)),
        ),
        (
            "Reblaze",
            _snapshot(headers=(("server", "Reblaze Secure Web Gateway"),)),
        ),
        (
            "Distil",
            _snapshot(body="<form id='distilCaptchaForm'></form>"),
        ),
        (
            "NAXSI",
            _snapshot(headers=(("x-data-origin", "naxsi/waf"),)),
        ),
        (
            "Zscaler",
            _snapshot(body="Internet Security by ZScaler"),
        ),
        (
            "StackPath",
            _snapshot(
                body=(
                    "is using a security service for protection against online attacks. "
                    "An action has triggered the service and blocked your request."
                ),
            ),
        ),
        (
            "BitNinja",
            _snapshot(body="Security check by BitNinja"),
        ),
        (
            "SonicWall",
            _snapshot(headers=(("server", "SonicWALL"),)),
        ),
        (
            "Palo Alto Next Generation Firewall",
            _snapshot(body="Palo Alto Next Generation Security Platform"),
        ),
        (
            "MalCare",
            _snapshot(body="Firewall powered by MalCare Pro"),
        ),
        (
            "SecuPress",
            _snapshot(body="<title>SecuPress</title>"),
        ),
        (
            "Safe3 Web Firewall",
            _snapshot(headers=(("server", "Safe3 Web Firewall"),)),
        ),
        (
            "Safedog",
            _snapshot(headers=(("x-safe-firewall", "on"),)),
        ),
        (
            "Wallarm",
            _snapshot(headers=(("server", "nginx-wallarm"),)),
        ),
        (
            "GoDaddy Website Protection",
            _snapshot(body="GoDaddy website firewall"),
        ),
        (
            "Shieldon Firewall",
            _snapshot(headers=(("x-protected-by", "shieldon.io"),)),
        ),
        (
            "XLabs Security WAF",
            _snapshot(headers=(("secured", "By XLabs Security"),)),
        ),
        (
            "TransIP Web Firewall",
            _snapshot(headers=(("x-transip-balancer", "edge"),)),
        ),
    )

    for expected, response in cases:
        assert expected in _names(response)
