from __future__ import annotations

import re
from dataclasses import dataclass

from wafdh.models import Confidence, Detection, DetectionSource, ResponseSnapshot


@dataclass(frozen=True, slots=True)
class WafRule:
    name: str
    manufacturer: str
    confidence: Confidence
    header_patterns: tuple[str, ...] = ()
    cookie_patterns: tuple[str, ...] = ()
    body_patterns: tuple[str, ...] = ()
    status_codes: tuple[int, ...] = ()


BUILTIN_RULES: tuple[WafRule, ...] = (
    WafRule(
        "Cloudflare",
        "Cloudflare",
        Confidence.HIGH,
        header_patterns=(r"server:\s*cloudflare", r"cf-ray:", r"cf-cache-status:"),
        cookie_patterns=(r"__cf_bm", r"cf_clearance"),
        body_patterns=(r"cloudflare ray id", r"attention required! \| cloudflare"),
    ),
    WafRule(
        "AWS WAF",
        "Amazon Web Services",
        Confidence.HIGH,
        header_patterns=(r"x-amzn-waf-", r"x-amz-cf-id:", r"x-amzn-requestid:"),
        body_patterns=(r"aws waf", r"generated by cloudfront"),
        status_codes=(403,),
    ),
    WafRule(
        "Akamai Kona",
        "Akamai",
        Confidence.HIGH,
        header_patterns=(r"akamai", r"akamai-ghost", r"x-akamai-"),
        cookie_patterns=(r"_abck", r"ak_bmsc", r"bm_sz"),
        body_patterns=(r"access denied \| akamai", r"reference #[0-9a-f.]+"),
    ),
    WafRule(
        "Imperva Incapsula",
        "Imperva",
        Confidence.HIGH,
        header_patterns=(r"incap_ses", r"x-iinfo:"),
        cookie_patterns=(r"visid_incap", r"incap_ses"),
        body_patterns=(r"incapsula incident id", r"powered by imperva"),
    ),
    WafRule(
        "F5 BIG-IP ASM",
        "F5",
        Confidence.HIGH,
        header_patterns=(r"bigipserver", r"f5-.*asm"),
        cookie_patterns=(r"bigipserver", r"ts[0-9a-f]{3,}="),
        body_patterns=(r"the requested url was rejected", r"support id:"),
    ),
    WafRule(
        "ModSecurity",
        "SpiderLabs",
        Confidence.HIGH,
        header_patterns=(r"mod_security", r"modsecurity"),
        body_patterns=(r"this error was generated by mod.?security", r"protected by mod.?security"),
        status_codes=(403, 406),
    ),
    WafRule(
        "Penta Security WAPPLES",
        "Penta Security",
        Confidence.HIGH,
        body_patterns=(
            r"web firewall security policies have been blocked",
            r"the request\s*/\s*response that are contrary",
            r"detect client ip",
            r"detect url",
            r"detect time",
            r"wapples",
            r"penta security",
        ),
    ),
)


class SignatureMatcher:
    def __init__(self, rules: tuple[WafRule, ...]) -> None:
        self._rules: tuple[WafRule, ...] = rules

    @property
    def rules(self) -> tuple[WafRule, ...]:
        return self._rules

    def match(self, responses: tuple[ResponseSnapshot, ...]) -> tuple[Detection, ...]:
        detections: list[Detection] = []
        for rule in self._rules:
            reason = _match_rule(rule, responses)
            if reason is None:
                continue
            detections.append(
                Detection(
                    source=DetectionSource.SIGNATURE,
                    name=rule.name,
                    manufacturer=rule.manufacturer,
                    confidence=rule.confidence,
                    reason=reason,
                )
            )
        return tuple(detections)


def load_rules() -> tuple[WafRule, ...]:
    return BUILTIN_RULES


def _match_rule(rule: WafRule, responses: tuple[ResponseSnapshot, ...]) -> str | None:
    for response in responses:
        header_blob = "\n".join(f"{key}: {value}" for key, value in response.headers)
        cookie_blob = "\n".join(value for key, value in response.headers if key == "set-cookie")
        if _matches(rule.header_patterns, header_blob):
            return f"{rule.name} header signature matched"
        if _matches(rule.cookie_patterns, cookie_blob):
            return f"{rule.name} cookie signature matched"
        if _matches(rule.body_patterns, response.body_excerpt):
            return f"{rule.name} body signature matched"
        if response.status_code in rule.status_codes and not _has_content_patterns(rule):
            return f"{rule.name} status code {response.status_code} matched"
    return None


def _has_content_patterns(rule: WafRule) -> bool:
    return len(rule.header_patterns) + len(rule.cookie_patterns) + len(rule.body_patterns) > 0


def _matches(patterns: tuple[str, ...], text: str) -> bool:
    return any(re.search(pattern, text, re.IGNORECASE) is not None for pattern in patterns)
